
---

- hosts: do
  remote_user: phyng
  become: yes
  vars:
    git_version: "master"
    project_root: "/home/phyng/project/rsshub"
    port: 8002
  tasks:

    - name: pull repo
      git:
        repo: https://github.com/phyng/rsshub.git
        dest: "{{ project_root }}"
        version: "{{ git_version }}"

    - name: create virtualenv
      pip:
        requirements: '{{ project_root }}/requirements.txt'
        virtualenv: '{{ project_root }}/env'

    - name: copy server_settings
      copy:
        src: "./rsshub/server_settings.py"
        dest: "{{ project_root }}/rsshub/server_settings.py"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

    - name: copy rsshub.conf
      copy:
        src: "./rsshub.conf"
        dest: "/etc/supervisor/conf.d/rsshub.conf"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

    - name: migrate
      command: "{{ project_root }}/env/bin/python {{ project_root }}/manage.py migrate"

    - name: collectstatic
      command: "{{ project_root }}/env/bin/python {{ project_root }}/manage.py collectstatic --noinput"

    - name: restart supervisor
      supervisorctl: name=rsshub state=restarted config=/etc/supervisor/supervisord.conf

    - name: "copy nginx conf"
      copy:
        src: "./rsshub_nginx.conf"
        dest: "/etc/nginx/sites-enabled/rsshub_nginx.conf"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

    - name: "test nginx"
      command: "nginx -t"

    - name: "reload nginx"
      command: "nginx -s reload"
