# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_rss_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
